all:
	g++ -std=c++17 PS11.cpp -o program
	./program

PS11:
	g++ -std=c++17 PS11.cpp -o program1
	./program1

PS12:
	g++ -std=c++17 PS12.cpp -o program2
	./program2

PS13:
	g++ -std=c++17 PS13.cpp -o program3
	./program3

clean:
	rm -f program*